services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /mnt/hdd/caddy/caddyfile:/etc/caddy
      - /mnt/hdd/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - /etc/localtime:/etc/localtime:ro
volumes:
  caddy_data: null
  caddy_config: null
networks: {}
