version: "3.3"
services:
  open-webui:
    ports:
      - 10500:8080
    volumes:
      - open-webui:/app/backend/data
    container_name: open-webui
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:dev
volumes:
  open-webui: {}
networks: {}
