services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    ports:
      - 10600:11434
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
volumes:
  ollama: {}
networks: {}
